const Minerals = [
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '1 - Iron Ore', price: 171 },
    { mineral: '2 - Iron Ore', price: 342 },
    { mineral: '2 - Iron Ore', price: 342 },
    { mineral: '2 - Iron Ore', price: 342 },
    { mineral: '2 - Iron Ore', price: 342 },
    { mineral: '2 - Iron Ore', price: 342 },
    { mineral: '2 - Iron Ore', price: 342 },
    { mineral: '2 - Iron Ore', price: 342 },
    { mineral: '2 - Iron Ore', price: 342 },
    { mineral: '2 - Iron Ore', price: 342 },
    { mineral: '2 - Iron Ore', price: 342 },
    { mineral: '3 - Iron Ore', price: 513 },
    { mineral: '3 - Iron Ore', price: 513 },
    { mineral: '3 - Iron Ore', price: 513 },
    { mineral: '3 - Iron Ore', price: 513 },
    { mineral: '3 - Iron Ore', price: 513 },
    { mineral: '3 - Iron Ore', price: 513 },
    { mineral: '3 - Iron Ore', price: 513 },
    { mineral: '3 - Iron Ore', price: 513 },
    { mineral: '3 - Iron Ore', price: 513 },
    { mineral: '3 - Iron Ore', price: 513 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '1 - Large Iron Ore', price: 855 },
    { mineral: '2 - Large Iron Ore', price: 1710 },
    { mineral: '2 - Large Iron Ore', price: 1710 },
    { mineral: '2 - Large Iron Ore', price: 1710 },
    { mineral: '2 - Large Iron Ore', price: 1710 },
    { mineral: '2 - Large Iron Ore', price: 1710 },
    { mineral: '2 - Large Iron Ore', price: 1710 },
    { mineral: '2 - Large Iron Ore', price: 1710 },
    { mineral: '2 - Large Iron Ore', price: 1710 },
    { mineral: '2 - Large Iron Ore', price: 1710 },
    { mineral: '2 - Large Iron Ore', price: 1710 },
    { mineral: '2 - Large Iron Ore', price: 1710 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 2 Tons of Nickel', price: 36 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - 3 Tons of Nickel', price: 54 },
    { mineral: '1 - Ounce of Gold', price: 1723 },
    { mineral: '1 - Ounce of Gold', price: 1723 },
    { mineral: '1 - Ounce of Gold', price: 1723 },
    { mineral: '1 - Ounce of Gold', price: 1723 },
    { mineral: '1 - 0.5 Carat Diamond', price: 1500 },
    { mineral: '1 - 0.5 Carat Diamond', price: 1500 },
    { mineral: '1 - Large Block of Gold', price: 55408 },
    { mineral: '1 - Large Block of Gold', price: 55408 },
    { mineral: '1 - Large Block of Gold', price: 55408 },
    { mineral: '1 - 1 Carat Diamond', price: 21000 },
    { mineral: '1 - 1 Carat Diamond', price: 21000 },
    { mineral: '1 - 2 Carat Diamond', price: 70000 },
    { mineral: '1 - 2 Carat Diamond', price: 70000 },
    { mineral: '2 - 2 Carat Diamond\n1 - Iron Ore', price: 70171 },
    { mineral: '2 - 2 Carat Diamond\n1 - Iron Ore', price: 70171 },
    { mineral: '2 - 2 Carat Diamond\n1 - 1 Ton of Gold', price: 125408 },
    { mineral: '1 - 3 Carat Diamond', price: 200000 },
    { mineral: '1 - 1 Carat Jadeite', price: 3000000 },
    { mineral: '2 - 1 Carat Jadeite', price: 6000000 },
    { mineral: '1 - 2 Carat Jadeite', price: 6000000 },
    { mineral: '2 - 2 Carat Jadeite', price: 12000000 },
    { mineral: '1 - 1 Carat Red Diamond', price: 2500000 },
    { mineral: '2 - 1 Carat Red Diamond', price: 5000000 },
    { mineral: '1 - 2 Carat Red Diamond', price: 5000000 },
    { mineral: '2 - 2 Carat Red Diamond', price: 10000000 },
    { mineral: '1 - 1 Carat Ruby Diamond', price: 1000000 },
    { mineral: '1 - 1 Carat Ruby Diamond', price: 1000000 },
    { mineral: '1 - 2 Carat Ruby Diamond', price: 2000000 },
    { mineral: '2 - 1 Carat Ruby Diamond', price: 2000000 },
    { mineral: '1 - 1 Carat Sapphire', price: 20500 },
    { mineral: '1 - 2 Carat Sapphire', price: 51000 },
    { mineral: '1 - 3 Carat Sapphire', price: 102000 },
    { mineral: '2 - 3 Carat Sapphire', price: 204000 },
    { mineral: '1 - 1 Carat Sapphire', price: 20500 },
    { mineral: '1 - 2 Carat Sapphire', price: 51000 },
    { mineral: '1 - 3 Carat Sapphire', price: 102000 },
    { mineral: '1 - 1 Carat Sapphire', price: 20500 },
    { mineral: '1 - 2 Carat Sapphire', price: 51000 },
    { mineral: '1 - 3 Carat Sapphire', price: 102000 },
    { mineral: '1 - Amethyst', price: 75 },
    { mineral: '2 - Amethyst', price: 150 },
    { mineral: '3 - Amethyst', price: 225 },
    { mineral: '5 - Amethyst', price: 370 },
    { mineral: '1 - Amethyst', price: 75 },
    { mineral: '2 - Amethyst', price: 150 },
    { mineral: '3 - Amethyst', price: 225 },
    { mineral: '5 - Amethyst', price: 370 },
    { mineral: '1 - Amethyst', price: 75 },
    { mineral: '2 - Amethyst', price: 150 },
    { mineral: '3 - Amethyst', price: 225 },
    { mineral: '5 - Amethyst', price: 370 },
    { mineral: '1 - Amethyst', price: 75 },
    { mineral: '2 - Amethyst', price: 150 },
    { mineral: '3 - Amethyst', price: 225 },
    { mineral: '1 - Amethyst', price: 75 },
    { mineral: '2 - Amethyst', price: 150 },
    { mineral: '1 - Amethyst', price: 75 },
    { mineral: '2 - Amethyst', price: 150 },
    { mineral: '1 - 1 Carat Rhodolite Garnet', price: 65 },
    { mineral: '1 - 1 Carat Rhodolite Garnet', price: 65 },
    { mineral: '1 - 1 Carat Rhodolite Garnet', price: 65 },
    { mineral: '1 - 1 Carat Rhodolite Garnet', price: 65 },
    { mineral: '1 - 1 Carat Rhodolite Garnet', price: 65 },
    { mineral: '1 - 1 Carat Rhodolite Garnet', price: 65 },
    { mineral: '1 - 2 Carat Rhodolite Garnet', price: 130 },
    { mineral: '1 - 2 Carat Rhodolite Garnet', price: 130 },
    { mineral: '1 - 2 Carat Rhodolite Garnet', price: 130 },
    { mineral: '1 - 2 Carat Rhodolite Garnet', price: 130 },
    { mineral: '1 - 2 Carat Rhodolite Garnet', price: 130 },
    { mineral: '2 - 1 Carat Rhodolite Garnet', price: 130 },
    { mineral: '2 - 1 Carat Rhodolite Garnet', price: 130 },
    { mineral: '2 - 1 Carat Rhodolite Garnet', price: 130 },
    { mineral: '2 - 1 Carat Rhodolite Garnet', price: 130 },
    { mineral: '1 - Spessartite Garnet', price: 2500 },
    { mineral: '1 - Spessartite Garnet', price: 2500 },
    { mineral: '2 - Spessartite Garnet', price: 5000 },
    { mineral: '2 - Spessartite Garnet', price: 5000 },
    { mineral: '1 - Demantoid Garnet', price: 1200 },
    { mineral: '1 - Demantoid Garnet', price: 1200 },
    { mineral: '1 - Demantoid Garnet', price: 1200 },
    { mineral: '1 - Rose Quartz', price: 10 },
    { mineral: '1 - Rose Quartz', price: 10 },
    { mineral: '1 - Rose Quartz', price: 10 },
    { mineral: '1 - Rose Quartz', price: 10 },
    { mineral: '1 - Rose Quartz', price: 10 },
    { mineral: '1 - Rose Quartz', price: 10 },
    { mineral: '1 - Rose Quartz', price: 10 },
    { mineral: '2 - Rose Quartz', price: 20 },
    { mineral: '2 - Rose Quartz', price: 20 },
    { mineral: '2 - Rose Quartz', price: 20 },
    { mineral: '2 - Rose Quartz', price: 20 },
    { mineral: '2 - Rose Quartz', price: 20 },
    { mineral: '3 - Rose Quartz', price: 30 },
    { mineral: '3 - Rose Quartz', price: 30 },
    { mineral: '3 - Rose Quartz', price: 30 },
    { mineral: '3 - Rose Quartz', price: 30 },
    { mineral: '3 - Rose Quartz', price: 30 },
    { mineral: '1 - Block of Rose Quartz', price: 100 },
    { mineral: '1 - Block of Rose Quartz', price: 100 },
    { mineral: '1 - Block of Rose Quartz', price: 100 },
    { mineral: '1 - Block of Rose Quartz', price: 100 },
    { mineral: '1 - Block of Rose Quartz', price: 100 },
    { mineral: '1 - 1 Carat Turqouise', price: 10 },
    { mineral: '1 - 1 Carat Turqouise', price: 10 },
    { mineral: '1 - 1 Carat Turqouise', price: 10 },
    { mineral: '1 - 1 Carat Turqouise', price: 10 },
    { mineral: '1 - 1 Carat Turqouise', price: 10 },
    { mineral: '1 - 1 Carat Turqouise', price: 10 },
    { mineral: '1 - 2 Carat Turqouise', price: 21 },
    { mineral: '1 - 2 Carat Turqouise', price: 21 },
    { mineral: '1 - 2 Carat Turqouise', price: 21 },
    { mineral: '1 - 2 Carat Turqouise', price: 21 },
    { mineral: '1 - 1 Ton of Copper', price: 6 },
    { mineral: '1 - 1 Ton of Copper', price: 6 },
    { mineral: '1 - 1 Ton of Copper', price: 6 },
    { mineral: '1 - 1 Ton of Copper', price: 6 },
    { mineral: '1 - 1 Ton of Copper', price: 6 },
    { mineral: '1 - 1 Ton of Copper', price: 6 },
    { mineral: '1 - 3 Ton of Copper', price: 18 },
    { mineral: '1 - 3 Ton of Copper', price: 18 },
    { mineral: '1 - 3 Ton of Copper', price: 18 },
    { mineral: '1 - 3 Ton of Copper', price: 18 },
    { mineral: '1 - 3 Ton of Copper', price: 18 },
    { mineral: '1 - 3 Ton of Copper', price: 18 },
]

module.exports = Minerals