const Peoples = [
    { name: 'MrBeast', message: 'Just for that, here\'s a $10 Grand :dollar:!', money: 10000, avatar: 'https://yt3.ggpht.com/a/AATXAJyQgC7foPvCExCarzV-kA3tuIinXYJRW3PYdA=s900-c-k-c0xffffffff-no-rj-mo' },
    { name: 'MrBeast', message: 'Just for that, here\'s a $10 Grand :dollar:!', money: 10000, avatar: 'https://yt3.ggpht.com/a/AATXAJyQgC7foPvCExCarzV-kA3tuIinXYJRW3PYdA=s900-c-k-c0xffffffff-no-rj-mo' },
    { name: 'MrBeast', message: 'Just for that, here\'s a $10 Grand :dollar:!', money: 10000, avatar: 'https://yt3.ggpht.com/a/AATXAJyQgC7foPvCExCarzV-kA3tuIinXYJRW3PYdA=s900-c-k-c0xffffffff-no-rj-mo' },
    { name: 'MrBeast', message: 'Just for that, here\'s a $10 Grand :dollar:!', money: 10000, avatar: 'https://yt3.ggpht.com/a/AATXAJyQgC7foPvCExCarzV-kA3tuIinXYJRW3PYdA=s900-c-k-c0xffffffff-no-rj-mo' },
    { name: 'MrBeast', message: 'Just for that, here\'s a $5,000 :dollar: Dollars!', money: 5000, avatar: 'https://yt3.ggpht.com/a/AATXAJyQgC7foPvCExCarzV-kA3tuIinXYJRW3PYdA=s900-c-k-c0xffffffff-no-rj-mo' },
    { name: 'MrBeast', message: 'Just for that, here\'s a $5,000 :dollar: Dollars!', money: 5000, avatar: 'https://yt3.ggpht.com/a/AATXAJyQgC7foPvCExCarzV-kA3tuIinXYJRW3PYdA=s900-c-k-c0xffffffff-no-rj-mo' },
    { name: 'MrBeast', message: 'Just for that, here\'s a $5,000 :dollar: Dollars!', money: 5000, avatar: 'https://yt3.ggpht.com/a/AATXAJyQgC7foPvCExCarzV-kA3tuIinXYJRW3PYdA=s900-c-k-c0xffffffff-no-rj-mo' },
    { name: 'MrBeast', message: 'Just for that, here\'s a $5,000 :dollar: Dollars!', money: 5000, avatar: 'https://yt3.ggpht.com/a/AATXAJyQgC7foPvCExCarzV-kA3tuIinXYJRW3PYdA=s900-c-k-c0xffffffff-no-rj-mo' },
    { name: 'Intense/Rune', message: 'Alright, you gave me a reasonable reason. I\'m going to give you $1,000,000 :dollar: Dollars.', money: 1000000, avatar: 'https://cdn.discordapp.com/avatars/564145650736955402/f8c388f95727b2391b354b2ffe5f2549.webp?size=4096'},
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Here :>', money: 1, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'fine', money: 2, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'fine', money: 2, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'fine', money: 2, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'fine', money: 2, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'fine', money: 2, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'fine', money: 2, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'fine', money: 2, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'fine', money: 2, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'fine', money: 2, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'fine', money: 2, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'fine', money: 2, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: '.u.', money: 20, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: '.u.', money: 20, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: '.u.', money: 20, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: '.u.', money: 20, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: '.u.', money: 20, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: '.u.', money: 20, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: '.u.', money: 20, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Time for my gambling addiction :D', money: 400, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Time for my gambling addiction :D', money: 400, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Time for my gambling addiction :D', money: 400, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
    { name: 'NaThAnZ', message: 'Time for my gambling addiction :D', money: 400, avatar: 'https://cdn.discordapp.com/embed/avatars/1.png' },
]

module.exports = Peoples